/** 
* 
*/
export const schemas = {
  SimpleMessage: {
    type: 'object',
    properties: {
      msg: {
        type: 'string'
      }
    }
  },
  User: {
    type: 'object',
    properties: {
      id: {
        type: 'integer',
        description: 'user id'
      },
      name: {
        type: 'string',
        description: 'user name'
      },
      email: {
        type: 'string',
        description: 'user email'
      },
      photo: {
        type: 'string',
        description: 'user profile photo url'
      }
    }
  },
  Encrypted: {
    type: 'object',
    properties: {
      secret: {
        type: 'string',
        description: 'be encrypted, used to generate signature'
      },
      sign: {
        type: 'string',
        description: 'signature by client side, generated by data and secret'
      },
      data: {
        type: 'string',
        description: 'encrypted data by client side'
      }
    }
  }
}